// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsEue6Xh0LbDmE34FgkNWGL-nhD2BFwL0',
    appId: '1:593065615362:web:24b9a2f1a27ac29bcd071b',
    messagingSenderId: '593065615362',
    projectId: 'staging-pontis',
    authDomain: 'staging-pontis.firebaseapp.com',
    storageBucket: 'staging-pontis.firebasestorage.app',
    measurementId: 'G-HVDE8198BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycsws6ww8hd6_bZWkp8yBaci_jPb4sUU',
    appId: '1:593065615362:android:5cdb1e3233448499cd071b',
    messagingSenderId: '593065615362',
    projectId: 'staging-pontis',
    storageBucket: 'staging-pontis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bq6yuUxojJS2dUK80GL1eX0rLCZmm8M',
    appId: '1:593065615362:ios:dedf7cdac288deaacd071b',
    messagingSenderId: '593065615362',
    projectId: 'staging-pontis',
    storageBucket: 'staging-pontis.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );
}
